### PR TITLE
Add support for django-cache-url

### PR DESCRIPTION
**Pull request by epicserve**
Added support for django-cache-url.

**Todo**
[x] Update the readme
[x] Fix one test that is failing locally

@sloria,

I have one test that is failing locally. Let me know if you have any ideas.
```
============================== FAILURES ==============================
___ TestEnvFileReading.test_read_env_not_found_with_verbose_warns ____

self = <test_environs.TestEnvFileReading object at 0x10e694070>
env = <Env {}>

    def test_read_env_not_found_with_verbose_warns(self, env):
        with pytest.warns(UserWarning) as record:
>           env.read_env("notfound", recurse=False, verbose=True)
E           Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) was emitted. The list of emitted warnings is: [].

tests/test_environs.py:233: Failed
------------------------- Captured log call --------------------------
WARNING  dotenv.main:main.py:67 File doesn't exist notfound
==================== 1 failed, 67 passed in 0.17s ====================
```

### CODE REVIEW

**Comment by epicserve** [comment]
@sloria,

Locking python-dotenv to 0.10.5 fixed the test. However, I'm not sure if that's how you want to solve it.

**Comment by epicserve** [comment]
Looks like it's related to this issue in [python-dotenv](https://github.com/theskumar/python-dotenv/pull/231)

**Comment by sloria** [comment]
We shouldn't pin python-dotenv because that could lead to version conflicts for users. I removed the test on dev since it is no longer accurate--it was a bit useless to test the implementation of an underlying library anyway.

Otherwise, this looks good. Thanks for the PR!

**Comment by epicserve** [comment]
@sloria,

Sounds good. I'm new to py.test so I was looking at what it would take to capture the logging with caplog and was getting a little lost with fixtures.

**Pull request merged**
