### PR TITLE
New timezone field

### PR DESCRIPTION
**Pull request by gnarvaja**
New timezone field casted to tzinfo using pytz module.

### CODE REVIEW

**Comment by hukkinj1** [comment]
We might want to consider using `dateutil.tz` instead of `pytz`.
- `dateutil.tz` is recommended by stdlib docs: https://docs.python.org/3/library/datetime.html#tzinfo-objects
- `dateutil.tz` is compatible with `datetime.tzinfo` interface: https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html
- `dateutil` seems to be more popular than `pytz` based on download count (https://hugovk.github.io/top-pypi-packages/). Projects are more likely to already have `dateutil` as dependency than `pytz`

**Comment by gnarvaja** [comment]
I added support for python-dateutil too. I kept support for pytz since it's the package used by Django and I guess many people uses environs with Django.

**Comment by sloria** [comment]
I'm not sure the added complexity and dependency is worth the benefit here. It's not too onerous to do

```python
tzinfo = pytz.timezone(env.timezone("TIMEZONE"))
```

That way we avoid changing behavior based on users' installed packages, which we've had bad experiences in other projects.

**Comment by sloria** [comment]
Closing for inactivity. For now, use `pytz.timezone(env.str("TIMEZONE"))`.

**Pull request closed without merging**
