### PR TITLE
Bugfix: Doesn't load env file through recursion

### PR DESCRIPTION
**Pull request by timoklimmer**
Another commit to fix a bug that prevents loading of custom-named .env files in upper directories. Follow-up to commit #155

### CODE REVIEW

**Comment by timoklimmer** [comment]
Any updates?

**Comment by sloria** [comment]
Sorry I haven't been able to review this in-depth. Haven't been able to find the focused time that this requires. This is more complexity than I was anticipating for this issue.

Without having looked into this thoroughly, I'm wondering if we can use [find_dotenv](https://github.com/theskumar/python-dotenv/blob/d83c1b65ceab5cf1223c41649a25a142755fe703/src/dotenv/main.py#L262) to do most of the searching logic? @timoklimmer Can you investigate this?

**Comment by sloria** [comment]
Also, for future reference: no need to send a new PR every time you make changes/respond to code review. Instead make a new branch for your PR and commit on that. I can take care of the squash and merge when all is said and done.

**Comment by timoklimmer** [comment]
"when all is said and done" - honestly, I don't want to have an endless conversation here. The only thing I am asking for is to get a small but relevant bug fixed in your package so I can use it without writing workaround code in my code. Others and I have already invested quite some time by writing PRs incl. the back-and-forth communication we had plus the unit tests, and now my fair expectation is that we get out the fix soon. 

I understand you don't have much time, and so do I. So my ask to you would be not to ask for new commits over and over about things you can quickly do on your own. Rather take the little time you have and adjust the PR as you think is needed so we can out the fix asap. Looking at the other PRs, there seem to be other people waiting for a fix too. They even provided PRs... 

Your idea to use find_dotenv does not work because it cannot cope with relative directories. A path like "tests/.custom.env" as in your unit tests leads to an exception. That's why I introduced merge_absolute_and_relative_path().

**Comment by sloria** [comment]
I do appreciate all the time you've put into this. It is my goal, too, to land the fix for this bug. It's not my intention to set up artificial barriers by nitpicking, etc. 

I often do make small fixups myself _if_ those are the only things to address before merging. That's not the case for this PR. There are multiple approaches to consider, and looking into these approaches and their side effects takes focused time. The approach in this PR adds a fair amount of custom code which--on a cursory glance--seems unnecessary given the functions available in `pathlib` and `dotenv`. It may be the case that this PR is the correct approach, but I want to make sure that alternative approaches are explored. I actually was planning to do this exploration myself this past weekend but wasn't able to find the time due to personal obligations.

For now, I'd recommend working around the issue by providing an direct path to the target `.env` file. 

```python
from pathlib import path

from environs import Env

HERE = Path(__file__).parent 
ENV = HERE / "path" / "to" / "custom.env"

env = Env()
env.read_env(ENV)
```


Hopefully I'll have some time this week to look further into this. All I ask from you is patience. We're on the same team here.

**Comment by sloria** [comment]
https://github.com/sloria/environs/pull/159 has the bug fix and is released in 8.0.0

**Pull request closed without merging**
